<a href="https://colab.research.google.com/github/NikolayLenkovNikolaev/R_for_Pharmacometrics/blob/main/Py1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [109]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Create a vector called _a_ containing the numbers 1 - 10

```
a <- 1:10
```

In [110]:
a = list(range(1, 11, 1))
a
b = [x for x in range(1,11)]
b

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

###  create a 2x2 matrix called 'ma' containing the numbers 1 - 4

```
# create a 2x2 matrix called 'ma' containing the numbers 1 - 4
ma <- matrix(c(1:4),
nrow = 2,
ncol = 2,
byrow = F
)
ma
##### Output:
[,1] [,2]
[1,] 1 3
[2,] 2 4
```

In [111]:
x = np.matrix(np.arange(1,5).reshape((2,2))).T
x

matrix([[1, 3],
        [2, 4]])

```
# a slightly different version of 'ma' when 'byrow=T'
ma <- matrix(c(1:4),
nrow = 2,
ncol = 2,
byrow = T
)
ma

Output:
[,1] [,2]
[1,] 1 2
[2,] 3 4
```

In [112]:
x = np.matrix(np.arange(1,5).reshape((2,2)))
x

matrix([[1, 2],
        [3, 4]])

```
# create a 2x2 matrix containing characters rather than numbers
# we do not specify 'byrow' so the default value of 'F' is used
clra <- c("red","white")
clrb <- c("blue","stars")
flag <- matrix(c(clra,clrb),
nrow = 2,
ncol = 2
)
flag

Output:
[,1] [,2]
[1,] "red" "blue"
[2,] "white" "stars"

```

In [113]:
clra = ["red", "blue"]
nlrb = ["blue", "stars"]

flag = [clra, nlrb]
flag

[['red', 'blue'], ['blue', 'stars']]

```
# can't mix data types in a matrix and get expected results
a <- 1:2
mixm <- matrix(c(clra,a),
nrow = 2,
ncol = 2
)

Output:
[,1] [,2]
[1,] "red" "1"
[2,] "white" "2"
```

In [114]:
a = np.arange(1,3)
mixm = np.hstack([a, clra])
type(mixm)
mixm.T


numpy.ndarray

array(['1', '2', 'red', 'blue'], dtype='<U21')

# List
```
breed <- c("beagle","irish setter", "mix")
ages <- c(1, 5, 3)
colors <- c("brown","tan","red")
Lsta <- list(breed, ages, colors)
Lsta

Output:
[[1]]
[1] "beagle" "irish setter" "mix"
[[2]]
[1] 1 5 3
[[3]]
[1] "brown" "tan" "red"
```

In [115]:
breed = ["beagle","irish setter", "mix"]
ages  = [1, 5, 3]
colors = ["brown","tan","red"]
Lsta = [breed, ages, colors]
for x in Lsta:
    print(x)

['beagle', 'irish setter', 'mix']
[1, 5, 3]
['brown', 'tan', 'red']


# we could have also created 'Lsta' in one step
Lsta <- list(breed = c("beagle","irish setter", "mix"),
ages = c(1, 5, 3),
colors = c("brown","tan","red")
)

In [116]:
[["beagle","irish setter", "mix"],
 [1, 5, 3],
 ["brown","tan","red"]]

[['beagle', 'irish setter', 'mix'], [1, 5, 3], ['brown', 'tan', 'red']]

# create a data frame called 'df1' from five vectors
id <- c(1,3,5,7)
age <- c(35, 46, 50, 25)
wt <- c(70, 100, 67, 40)
sex <- as.factor(c("male","male","female","male")
)
trt <- as.logical(c('T','F','T',NA)
)
df1 <- data.frame(id, age, wt, sex, trt)
# typing the data frame name (df1) at the R prompt
# prints out the components of df1
df1

In [117]:
id  = [1,3,5,7]
age = [35, 46, 50, 25]
wt  = [70, 100, 67, 40]
sex = ["male","male","female","male"]
trt = ['T','F','T', "NaN"]

df = pd.DataFrame([id, age, wt, sex, trt]).T
df.columns =  ["id", "age", "wt", "sex", "trt"]
df

id age   wt     sex  trt
0  1  35   70    male    T
1  3  46  100    male    F
2  5  50   67  female    T
3  7  25   40    male  NaN

In [118]:
df.describe()

id  age  wt   sex trt
count    4    4   4     4   4
unique   4    4   4     2   3
top      1   35  70  male   T
freq     1    1   1     3   2

In [120]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      4 non-null      object
 1   age     4 non-null      object
 2   wt      4 non-null      object
 3   sex     4 non-null      object
 4   trt     4 non-null      object
dtypes: object(5)
memory usage: 288.0+ bytes


# 1.5. Create R Objects and Perform Simple Operations

```
a <- c(1,2,3,6,10)
```

In [121]:
a = [1,2,3,6,10]

```
b <- c(1:5)
b1 <- seq(from=1,to=5)
```

In [126]:
b = list(range(1,6))
b

[1, 2, 3, 4, 5]

```
b2 <- seq(from=1, to=5, by=0.5)
b2
```

In [130]:
b = np.arange(1,6, 0.5)
b

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

```
d <- c(3,4)
d1 <- rep(d, times=4)
d1
```

In [131]:
d = [3,4]*4
d

[3, 4, 3, 4, 3, 4, 3, 4]

# Vector operations

```
a <- c(1:5)
b <- c(2:6)
a+b
[1] 3 5 7 9 11
```

In [134]:
a = np.arange(1,6)
b = np.arange(2,7)
a+b

array([ 3,  5,  7,  9, 11])

```
a <- c(1:5)
b <- 2
c <- 1
a*b+c
```

In [140]:
a = np.arange(1, 6)
b = np.array(2)
c = np.array(1)
a
b
c

np.multiply(a, b) + c

array([1, 2, 3, 4, 5])

array(2)

array(1)

array([ 3,  5,  7,  9, 11])

```
a <- data.frame(
    "time" = c(0:10),
    "conc" = c(0, 20, 100, 96, 94, 92, 90, 60, 30, 5, 1),
    "dose" = rep(5,11)
)

a$conc <- a$conc * 10

# we have multiplied the "conc" column by 10 and put the
# new values back into the 'a' data frame

a$conc10 <- a$conc * 10
```

In [159]:
time = list(range(0,11))
conc = [0, 20, 100, 96, 94, 92, 90, 60, 30, 5, 1]
dose = [5]*11

dict = {"time": time, "conc": conc, "dose": dose}
df = pd.DataFrame(dict)
df

11

11

11

time  conc  dose
0      0     0     5
1      1    20     5
2      2   100     5
3      3    96     5
4      4    94     5
5      5    92     5
6      6    90     5
7      7    60     5
8      8    30     5
9      9     5     5
10    10     1     5

In [160]:
df["conc10"] = df["conc"]*10
df

time  conc  dose  conc10
0      0     0     5       0
1      1    20     5     200
2      2   100     5    1000
3      3    96     5     960
4      4    94     5     940
5      5    92     5     920
6      6    90     5     900
7      7    60     5     600
8      8    30     5     300
9      9     5     5      50
10    10     1     5      10

# Subset
```
# data frame 'a' contains three columns
# with 11 rows per column
# select only the 'time' and 'conc' columns and
# place in new data frame call 'f1'
f1 <- a[ ,c("time","conc")]
#or
f1 <- a[ ,c(1,2)]
```

In [169]:
f1 = df[["time", "conc"]]
f1.head()

time  conc
0     0     0
1     1    20
2     2   100
3     3    96
4     4    94

In [168]:
f2 = df.iloc[:, [0,1]]
f2.head()

time  conc
0     0     0
1     1    20
2     2   100
3     3    96
4     4    94

# Select a row or set of rows:
```
# select only the first 5 rows and all columns
f2 <- a[1:5,]
# select a$time <=5
f3 <- a[a$time<=5,]
```

In [173]:
f2 = df.iloc[:4]
f2

time  conc  dose  conc10
0     0     0     5       0
1     1    20     5     200
2     2   100     5    1000
3     3    96     5     960

In [177]:
f3 = df[df["time"] <= 5]
f3

time  conc  dose  conc10
0     0     0     5       0
1     1    20     5     200
2     2   100     5    1000
3     3    96     5     960
4     4    94     5     940
5     5    92     5     920